import { create } from 'zustand'
import { STUDIO_DATA } from '@/data/studio-data'
import { useCustomRoles } from '@/stores/custom-roles'
import { useWorkspace } from '@/stores/workspace'
import { attachVerifyListeners } from '@/stores/verify'
import { roleHasAgent, roleIsCoordinator, uid, applySubToolStart, applySubToolDone, applySubToolDelta, locateSubToolMsgIndex, SHOWN_SERVER_BLOCKS } from './chat-helpers'
import type { ApprovalCard, ChatMessage, ChatState, MsgBlock } from './chat-types'

// Unified per-conversation chat store (L3). A conversation is a real DB row; messages persist to the
// messages table. Every role is a chat; a role whose id is in AGENT_ROLES has its replies generated by
// the agent (tool use over agent:* IPC) instead of plain text streaming (chat:* IPC). The store routes
// the send + accumulates both event streams into the same byConversation message list — agent turns
// additionally carry tool cards + may raise a permission prompt.

// Re-export the store's public types + role predicates: consumers import them from '@/stores/chat' (the
// store's API face) even though their definitions now live in chat-types.ts / chat-helpers.ts.
export type { ToolCall, MsgBlock, ChatMessage, ServerNote, PermissionPrompt, QuestionPrompt, ApprovalCard } from './chat-types'
export { roleHasAgent, roleHasImageGen } from './chat-helpers'

type Meta = { convId: string; expertId: string; endpointId: string; model: string }
const streamMeta = new Map<string, Meta>() // chat (plain text) path: streamId → conversation
const agentMeta = new Map<string, Meta>() // agent (tool use) path: streamId → conversation
const coordinatorMeta = new Map<string, { convId: string; endpointId: string; model: string }>() // coordinator: streamId → conversation
let creating = false // sync guard: blocks a double-create when a fresh thread's first message fires twice
let listening = false

export const useChat = create<ChatState>((set, get) => {
  // Append a text delta into a message's ordered block list: extend the trailing text block, or open a new
  // one if the list is empty or ends in a tool block (text emitted AFTER a tool call → its own segment, so
  // the renderer interleaves it below that tool card). Keeps blocks in sync with cur.text on every delta.
  const pushTextDelta = (cur: ChatMessage, text: string): void => {
    const blocks = cur.blocks ? [...cur.blocks] : []
    const last = blocks[blocks.length - 1]
    if (last && last.kind === 'text') blocks[blocks.length - 1] = { kind: 'text', text: last.text + text }
    else blocks.push({ kind: 'text', text })
    cur.blocks = blocks
  }

  // Append a text delta to the last streaming assistant message; start a fresh one if the last isn't
  // streaming. Agent turns are multi-step (assistant → tool results → assistant …) so each new turn
  // becomes its own message, leaving the prior turn's text + tool cards intact.
  const appendDelta = (convId: string, text: string): void => {
    set((s) => {
      const msgs = (s.byConversation[convId] ?? []).map((m) => ({ ...m }))
      let cur = msgs[msgs.length - 1]
      if (!cur || cur.role !== 'assistant' || !cur.streaming) {
        cur = { id: uid(), role: 'assistant', text: '', streaming: true }
        msgs.push(cur)
      }
      cur.text += text
      pushTextDelta(cur, text)
      return { byConversation: { ...s.byConversation, [convId]: msgs } }
    })
  }

  // Attach a generated image (nsai-media:// url) to the current streaming assistant message. An agent tool
  // (Georgia's ns_generate_image, code_execution charts) produced it; the image is ready when this fires
  // (the tool ran synchronously), so it lands directly on the live bubble — no loading placeholder.
  const appendImage = (convId: string, image: { url: string; name: string }): void => {
    set((s) => {
      const msgs = (s.byConversation[convId] ?? []).map((m) => ({ ...m }))
      let cur = msgs[msgs.length - 1]
      if (!cur || cur.role !== 'assistant' || !cur.streaming) {
        cur = { id: uid(), role: 'assistant', text: '', streaming: true }
        msgs.push(cur)
      }
      cur.images = [...(cur.images ?? []), image]
      return { byConversation: { ...s.byConversation, [convId]: msgs } }
    })
  }

  // Coordinator parallel panel: experts stream CONCURRENTLY, so "the last bubble" (appendDelta) would
  // interleave their text. Route each delta to the streaming bubble tagged with its roleId instead.
  const appendDeltaToRole = (convId: string, roleId: string, text: string): void => {
    set((s) => {
      const msgs = (s.byConversation[convId] ?? []).map((m) => ({ ...m }))
      for (let i = msgs.length - 1; i >= 0; i--) {
        if (msgs[i].role === 'assistant' && msgs[i].streaming && msgs[i].expertId === roleId) {
          const cur = { ...msgs[i], text: msgs[i].text + text }
          pushTextDelta(cur, text) // keep the ordered block stream in sync (interleave with this step's tool cards)
          msgs[i] = cur
          return { byConversation: { ...s.byConversation, [convId]: msgs } }
        }
      }
      return s // no matching streaming bubble yet (step:start creates it first) — drop rather than mis-route
    })
  }

  // Coordinator: route a dispatched step's live usage to ITS streaming bubble (per-segment), so concurrent
  // segments each show their own ↑/↓ instead of all reading the shared conv-level overlay (BUG 2). Walks back
  // to the streaming assistant tagged with this roleId (parallel panels finish out of order).
  const updateSegmentLive = (convId: string, roleId: string, inputTokens: number, outputTokens?: number, cachedTokens?: number): void => {
    set((s) => {
      const cur = s.byConversation[convId]
      if (!cur) return s
      for (let i = cur.length - 1; i >= 0; i--) {
        const m = cur[i]
        if (m.role === 'assistant' && m.streaming && m.expertId === roleId) {
          const msgs = cur.map((x) => ({ ...x }))
          msgs[i].liveInputTokens = inputTokens
          if (outputTokens !== undefined) msgs[i].liveOutputTokens = outputTokens
          if (cachedTokens !== undefined) msgs[i].liveCachedTokens = cachedTokens
          return { byConversation: { ...s.byConversation, [convId]: msgs } }
        }
      }
      return s
    })
  }

  const ensureListeners = (): void => {
    if (listening) return
    listening = true

    // Gate C e2e verification (verify:progress / verify:tool / verify:done, keyed by convId): wired here so it
    // shares this one-time subscription lifecycle with the coordinator/agent listeners (no double-subscribe).
    attachVerifyListeners()

    // Clear a conversation's "retrying" banner once a run makes progress again (or ends). Shared by the
    // chat and agent paths — both set the same store.retry[convId].
    const clearRetry = (convId: string): void =>
      set((s) => (s.retry[convId] ? { retry: { ...s.retry, [convId]: null } } : s))

    // ---- chat (plain text) path: chat:delta / chat:done / chat:error / chat:retry ----
    const api = window.api.chat
    api.onDelta((d) => {
      const meta = streamMeta.get(d.streamId)
      if (!meta) return
      appendDelta(meta.convId, d.text)
      clearRetry(meta.convId)
    })
    api.onRetry((d) => {
      const meta = streamMeta.get(d.streamId)
      if (!meta) return
      set((s) => ({
        retry: {
          ...s.retry,
          [meta.convId]: { attempt: d.attempt, max: d.max, since: s.retry[meta.convId]?.since ?? Date.now() }
        }
      }))
    })
    api.onDone(async (d) => {
      const meta = streamMeta.get(d.streamId)
      streamMeta.delete(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        const cur = msgs[msgs.length - 1]
        if (cur && cur.role === 'assistant') {
          cur.streaming = false
          cur.text = d.text // done is authoritative
          if (typeof d.inputTokens === 'number') cur.inputTokens = d.inputTokens
          if (typeof d.usage?.outTokens === 'number') cur.outputTokens = d.usage.outTokens
          if (typeof d.usage?.inTokens === 'number') cur.sentTokens = d.usage.inTokens
        }
        return {
          byConversation: { ...s.byConversation, [meta.convId]: msgs },
          streaming: { ...s.streaming, [meta.convId]: false },
          retry: { ...s.retry, [meta.convId]: null }
        }
      })
      const ctxTok = d.inputTokens
      if (typeof ctxTok === 'number')
        set((s) => ({ contextTokens: { ...s.contextTokens, [meta.convId]: ctxTok } }))
      // B6/#8: persist the assistant turn, THEN extract memory, THEN fire compaction — all before the fold —
      // so the documented "extract synchronously before folding" ordering holds EXPLICITLY rather than by
      // relying on the append IPC happening to land before onTurn. Awaiting the append makes it robust even
      // if the append handler is ever made async; onTurn (extraction) then runs before compaction so its own
      // STEP 0 extraction can't lose the CAS lock and fold before memory is captured. onTurn runs an LLM
      // extraction only on its cadence turns; other turns it resolves immediately. Best-effort — neither the
      // extraction nor the list refresh may block compaction.
      await window.api.conversations
        .append(meta.convId, { author: 'expert', expertId: meta.expertId, model: meta.model, content: d.text, inputTokens: ctxTok, outputTokens: d.usage?.outTokens, sentTokens: d.usage?.inTokens })
        .catch(() => {})
      void get().loadConversations()
      await window.api.memory
        .onTurn({ convId: meta.convId, roleId: meta.expertId, endpointId: meta.endpointId, model: meta.model })
        .catch(() => {})
      void window.api.chat.compress({ convId: meta.convId, roleId: meta.expertId, endpointId: meta.endpointId, model: meta.model, currentTokens: ctxTok })
    })
    api.onError((d) => {
      const meta = streamMeta.get(d.streamId)
      streamMeta.delete(d.streamId)
      if (meta) {
        clearRetry(meta.convId)
        finishWithError(meta.convId, d.message)
      }
    })

    // ---- agent (tool use) path: agent:delta / assistant / results / permission / done / error ----
    // The backend persists the user + final assistant turn itself; here we only accumulate the live UI
    // (text + tool cards) and the permission prompt. We never re-append the assistant message.
    const ag = window.api.agent
    // 批C2b: a parked solo run resumed itself on a fresh stream (a launched async op completed). Bind the new
    // streamId to its conversation — every agent:* handler below is keyed by agentMeta.get(streamId), so this one
    // line routes the entire resumed turn (deltas, tool cards, done) into the conv without touching them. Mark the
    // conv streaming so the composer shows the live working state; onDone clears it. A fresh assistant bubble opens
    // on the first delta (appendDelta starts one when the last message isn't a live assistant turn).
    ag.onResumeStream((d) => {
      agentMeta.set(d.streamId, { convId: d.convId, expertId: d.roleId, endpointId: d.endpointId, model: d.model })
      set((s) => ({ streaming: { ...s.streaming, [d.convId]: true } }))
    })
    ag.onDelta((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      appendDelta(meta.convId, d.text)
      clearRetry(meta.convId)
    })
    // A tool just started (streamed before the turn finishes) — show a running card immediately so the
    // user sees the call in flight instead of silence until onAssistant. The full input (and the card's
    // summary) arrives when the turn completes; onAssistant then overwrites cur.tools with the authoritative
    // blocks (same tool_use id, so no duplicate).
    ag.onToolStart((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m, tools: m.tools ? [...m.tools] : m.tools }))
        let cur = msgs[msgs.length - 1]
        if (!cur || cur.role !== 'assistant' || !cur.streaming) {
          cur = { id: uid(), role: 'assistant', text: '', streaming: true, tools: [] }
          msgs.push(cur)
        }
        if (!cur.tools?.some((t) => t.id === d.id)) {
          cur.tools = [...(cur.tools ?? []), { id: d.id, name: d.name, input: {}, status: 'running' as const }]
          // Record the tool's position in the ordered block stream (after whatever text streamed before it),
          // so the renderer slots its card between the preceding and following text segments.
          cur.blocks = [...(cur.blocks ?? []), { kind: 'tool', id: d.id }]
        }
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    // Card-anchored to ONE message (locateSubToolMsgIndex), NOT mapped over EVERY message — the old `.map`
    // applied each sub-tool to all messages, so panel_examine's sentinel parent ('coordinator-gate-b', matched
    // by nothing) hit the orphan-append on every message → a panel card duplicated after every block. Same
    // routing the coordinator path uses; '' roleId → the agent path's streaming-message fallback.
    ag.onSubToolStart((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        const i = locateSubToolMsgIndex(msgs, '', d.parentToolId, d.toolUseId)
        if (i >= 0) msgs[i] = applySubToolStart(msgs[i], d.parentToolId, d.toolUseId, d.name, d.input)
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    ag.onSubToolDone((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        const i = locateSubToolMsgIndex(msgs, '', d.parentToolId, d.toolUseId)
        if (i >= 0) msgs[i] = applySubToolDone(msgs[i], d.parentToolId, d.toolUseId, d.name, d.result, d.isError, d.input)
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    ag.onSubToolDelta((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        const i = locateSubToolMsgIndex(msgs, '', d.parentToolId, d.toolUseId)
        if (i >= 0) msgs[i] = applySubToolDelta(msgs[i], d.parentToolId, d.toolUseId, d.delta)
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    ag.onAssistant((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      clearRetry(meta.convId) // a turn arrived → no longer retrying
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        let cur = msgs[msgs.length - 1]
        if (!cur || cur.role !== 'assistant' || !cur.streaming) {
          cur = { id: uid(), role: 'assistant', text: '', streaming: true }
          msgs.push(cur)
        }
        cur.text = d.blocks
          .filter((b): b is { type: 'text'; text: string } => b.type === 'text')
          .map((b) => b.text)
          .join('') // onAssistant is authoritative for the turn's text (deltas were a preview)
        const existingTools = new Map((cur.tools ?? []).map((t) => [t.id, t]))
        cur.tools = d.blocks
          .filter((b): b is { type: 'tool_use'; id: string; name: string; input: unknown } => b.type === 'tool_use')
          .map((b) => ({
            id: b.id,
            name: b.name,
            input: b.input,
            status: 'running' as const,
            subTools: existingTools.get(b.id)?.subTools,
          }))
        // Authoritative ORDER for the turn: rebuild the block list straight from d.blocks (text + tool_use in
        // emission order). This corrects whatever the delta/onToolStart preview accumulated — the renderer
        // now interleaves text and tool cards exactly as the model emitted them. (server blocks render
        // separately as faint status rows, so they're not part of the interleave.)
        cur.blocks = d.blocks
          .filter((b): b is { type: 'text'; text: string } | { type: 'tool_use'; id: string; name: string; input: unknown } => b.type === 'text' || b.type === 'tool_use')
          .map((b) => (b.type === 'text' ? { kind: 'text' as const, text: b.text } : { kind: 'tool' as const, id: b.id }))
        cur.servers = d.blocks
          .filter((b): b is { type: 'server'; serverType: string; query?: string; url?: string } => b.type === 'server' && SHOWN_SERVER_BLOCKS.has(b.serverType))
          .map((b) => ({ serverType: b.serverType, query: b.query, url: b.url }))
        // Sources = the answer's url citations, or — when the model returns none — the sites web_search
        // actually visited (open_page). Some web_search responses carry visited pages but no inline
        // url_citation annotations, so without this fallback the Sources list would be empty.
        const seenCite = new Set<string>()
        const textCites = d.blocks.flatMap((b) => (b.type === 'text' ? (b.citations ?? []) : []))
        const visited = d.blocks.flatMap((b) =>
          b.type === 'server' && b.serverType === 'web_search_call' && b.url ? [{ url: b.url }] : []
        )
        const cites = (textCites.length ? textCites : visited).filter((c) => (seenCite.has(c.url) ? false : (seenCite.add(c.url), true)))
        cur.citations = cites.length ? cites : undefined
        cur.streaming = false // turn complete; the next turn (after results) starts a new message
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    ag.onResults((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m, tools: m.tools ? [...m.tools] : m.tools }))
        for (const r of d.results) {
          // apply to the most recent message holding a still-running tool with that id
          for (let i = msgs.length - 1; i >= 0; i--) {
            const idx = msgs[i].tools?.findIndex((t) => t.id === r.toolUseId && t.status === 'running') ?? -1
            if (idx !== -1 && msgs[i].tools) {
              msgs[i].tools![idx] = { ...msgs[i].tools![idx], status: r.isError ? 'error' : 'done', result: r.content }
              break
            }
          }
        }
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    ag.onPermission((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => ({
        permission: { ...s.permission, [meta.convId]: { permissionId: d.permissionId, toolName: d.toolName, input: d.input, reason: d.reason, source: 'agent', roleId: meta.expertId } }
      }))
    })
    ag.onPermissionCancel((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => (s.permission[meta.convId]?.permissionId === d.permissionId ? { permission: { ...s.permission, [meta.convId]: null } } : {}))
    })
    ag.onQuestion((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => ({
        question: { ...s.question, [meta.convId]: { questionId: d.questionId, question: d.question, header: d.header, options: d.options, roleId: meta.expertId } }
      }))
    })
    ag.onQuestionCancel((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => (s.question[meta.convId]?.questionId === d.questionId ? { question: { ...s.question, [meta.convId]: null } } : {}))
    })
    ag.onDone((d) => {
      const meta = agentMeta.get(d.streamId)
      agentMeta.delete(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        const cur = msgs[msgs.length - 1]
        if (cur && cur.role === 'assistant') {
          cur.streaming = false
          if (typeof d.inputTokens === 'number') cur.inputTokens = d.inputTokens
          if (typeof d.outputTokens === 'number') cur.outputTokens = d.outputTokens
          if (typeof d.sentTokens === 'number') cur.sentTokens = d.sentTokens // SETTLE ↑: cumulative total sent this run
        }
        return {
          byConversation: { ...s.byConversation, [meta.convId]: msgs },
          streaming: { ...s.streaming, [meta.convId]: false },
          permission: { ...s.permission, [meta.convId]: null },
          retry: { ...s.retry, [meta.convId]: null },
          // The "/ window" meter keeps the value the live usage stream maintained during the run.
          // d.inputTokens here is the LAST turn's actual prompt (agent-dispatch lastContext) — after a
          // long run microcompact has cleared most tool results, so it can be a fraction of the
          // conversation's real occupancy (round11: 279K during the run → 17.9K the moment it ended,
          // a visible jump). The next send re-measures via countContext anyway; only fill when the
          // live stream never produced a value (degenerate short runs).
          contextTokens:
            typeof d.inputTokens === 'number' && s.contextTokens[meta.convId] === undefined
              ? { ...s.contextTokens, [meta.convId]: d.inputTokens }
              : s.contextTokens
        }
      })
      void get().loadConversations() // backend persisted the final reply + maybe a title
    })
    ag.onError((d) => {
      const meta = agentMeta.get(d.streamId)
      agentMeta.delete(d.streamId)
      if (meta) {
        clearRetry(meta.convId)
        finishWithError(meta.convId, d.message)
      }
    })
    ag.onRetry((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      // Keep `since` from the first retry so the readout shows total time spent retrying, not per-attempt.
      set((s) => ({
        retry: {
          ...s.retry,
          [meta.convId]: { attempt: d.attempt, max: d.max, since: s.retry[meta.convId]?.since ?? Date.now() }
        }
      }))
    })
    // Per-conversation usage, broadcast by EVERY path (chat / agent / coordinator / image). Three kinds ride
    // this channel and must NOT be conflated (see ConvUsage / token accumulation spec):
    //   • 'context' — the CURRENT context size (count_tokens of the turn being sent), measured up front per
    //     turn → contextTokens, which the composer's "/ window" indicator reads. Roughly constant per turn,
    //     bounded by the model window.
    //   • 'live'    — the in-flight request's REAL ↑prompt/↓output → liveInput / liveOutput, which feed the
    //     current live overlay only. Every ping OVERWRITES (each request reports its own full prompt size,
    //     so ↑ tracks current context in real time) — never accumulate these.
    //   • 'turn-final' — exactly-once final usage for a single LLM request → session accumulators.
    window.api.onConvUsage((d) => {
      // Coordinator dispatched sub-step (roleId present, not the coordinator's own line) → this usage belongs
      // to ONE segment, not the conversation: route it to that segment's streaming bubble (so concurrent
      // segments don't all show the conv-level total — BUG 2) and keep its context OUT of the composer /window
      // meter (a small-context verifier step must not shrink it — BUG 1). chat/agent paths and the coordinator's
      // own steps carry no sub-step roleId → conv-level behaviour below, unchanged.
      const seg = d.roleId && d.roleId !== 'coordinator' ? d.roleId : null
      if (d.kind === 'context') {
        if (seg) updateSegmentLive(d.convId, seg, d.inputTokens, undefined)
        else set((s) => ({ contextTokens: { ...s.contextTokens, [d.convId]: d.inputTokens } }))
      } else if (d.kind === 'live') {
        if (seg) {
          updateSegmentLive(d.convId, seg, d.inputTokens, d.outputTokens, d.cacheReadInputTokens)
        } else {
          set((s) => ({
            liveInput: { ...s.liveInput, [d.convId]: d.inputTokens },
            // Real output only rides the streaming pings that carry it; one without output keeps the last value
            // so ↓ stays visible next to ↑ across the whole turn instead of flickering to an estimate.
            liveOutput: typeof d.outputTokens === 'number' ? { ...s.liveOutput, [d.convId]: d.outputTokens } : s.liveOutput,
            liveCached: typeof d.cacheReadInputTokens === 'number' ? { ...s.liveCached, [d.convId]: d.cacheReadInputTokens } : s.liveCached
          }))
        }
      } else if (d.kind === 'turn-final') {
        // A request completed. Clear the live overlay so the readout falls back to the current context size
        // instead of lingering on this request's last streamed cumulative ping until the next request starts.
        set((s) => ({
          liveInput: { ...s.liveInput, [d.convId]: 0 },
          liveOutput: { ...s.liveOutput, [d.convId]: 0 },
          liveCached: { ...s.liveCached, [d.convId]: 0 }
        }))
      }
    })

    // Live generated images from an in-flight agent turn (Georgia's ns_generate_image, code_execution
    // charts): the loop persisted the image to the media store and broadcasts its nsai-media:// ref here.
    // Attach it to the streaming assistant bubble immediately — the tool runs synchronously (the card spinner
    // is the "generating" indicator), so the ready image lands without a placeholder. It's also persisted on
    // the final assistant message, so a reopened conversation re-reads it from the DB (openConversation).
    window.api.onConvImage((d) => {
      appendImage(d.convId, { url: d.attachment.url, name: d.attachment.name ?? 'image' })
    })

    // ---- coordinator (router + multi-expert dispatch) path ----
    // Event lifecycle per turn:
    //   1. step:start arrives BEFORE any delta for that step. We rebind the placeholder assistant
    //      message (created in send() optimistically) to the actual roleId for the first step, and
    //      attach the dispatch chain (pipeline only — single mode passes dispatch=null). Subsequent
    //      step:start events APPEND a fresh streaming assistant message tagged with that step's role.
    //   2. delta accumulates text into the most recent streaming assistant.
    //   3. step:done marks the current message non-streaming + sets the authoritative text.
    //   4. done clears the conversation's streaming flag + reloads history.
    const at = window.api.coordinator
    at.onDispatch(() => {
      // chain is already stored per-message via step:start.dispatch; nothing global to update here.
      // Future: surface decision.reason as a debug tooltip on the badge.
    })
    at.onStepStart((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        // Optimistic placeholder from send() is the FIRST step's slot (tail, no expertId yet) — reuse it.
        const cur = msgs[msgs.length - 1]
        if (cur && cur.role === 'assistant' && cur.streaming && !cur.expertId) {
          cur.expertId = d.roleId
          cur.dispatch = d.dispatch
          cur.segmentKind = d.segmentKind ?? null
        } else {
          // Else adopt this role's un-adopted streaming PLACEHOLDER anywhere in the list — a sub-tool event (e.g.
          // a panel_examine card) may have opened the role's bubble before this step:start, and it is not
          // necessarily the tail if another role's event interleaved. Walk back like the sibling handlers; a
          // placeholder is identified by `dispatch === undefined` (a real step's bubble always has dispatch set,
          // even to null), so we fill it in place instead of stranding it into a duplicate same-role segment.
          let adopt = -1
          for (let i = msgs.length - 1; i >= 0; i--) {
            const m = msgs[i]
            if (m.role === 'assistant' && m.streaming && m.expertId === d.roleId && m.dispatch === undefined) { adopt = i; break }
          }
          if (adopt >= 0) {
            msgs[adopt] = { ...msgs[adopt], dispatch: d.dispatch, segmentKind: d.segmentKind ?? null }
          } else {
            msgs.push({ id: uid(), role: 'assistant', text: '', streaming: true, expertId: d.roleId, dispatch: d.dispatch, segmentKind: d.segmentKind ?? null })
          }
        }
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    at.onDelta((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (meta) appendDeltaToRole(meta.convId, d.roleId, d.text)
    })
    at.onStepDone((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        // Find THIS role's streaming bubble — parallel panels finish out of order, so the last bubble
        // isn't necessarily this step's. step:done text is authoritative over the delta accumulator.
        for (let i = msgs.length - 1; i >= 0; i--) {
          if (msgs[i].role === 'assistant' && msgs[i].streaming && msgs[i].expertId === d.roleId) {
            msgs[i] = { ...msgs[i], text: d.text, streaming: false, ...(typeof d.inputTokens === 'number' ? { inputTokens: d.inputTokens } : {}), ...(typeof d.outputTokens === 'number' ? { outputTokens: d.outputTokens } : {}), ...(typeof d.sentTokens === 'number' ? { sentTokens: d.sentTokens } : {}) }
            break
          }
        }
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    at.onDone((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      coordinatorMeta.delete(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        // Belt-and-suspenders: clear streaming flag on the last assistant (in case step:done was missed).
        const cur = msgs[msgs.length - 1]
        if (cur && cur.role === 'assistant') {
          cur.streaming = false
          if (cur.inputTokens === undefined && typeof d.inputTokens === 'number') cur.inputTokens = d.inputTokens
          if (cur.outputTokens === undefined && typeof d.outputTokens === 'number') cur.outputTokens = d.outputTokens
        }
        // Finalize ANY other leftover streaming assistant bubble at run end — e.g. a never-adopted placeholder
        // (a sub-tool card opened a role bubble whose step:start never arrived) would otherwise stream a phantom
        // "Thinking…" forever, since step:done/the tail-clear only touch the last message.
        for (let i = 0; i < msgs.length - 1; i++) {
          if (msgs[i].role === 'assistant' && msgs[i].streaming) msgs[i] = { ...msgs[i], streaming: false }
        }
        // The "/ window" meter shows the CURRENT context of the COMPOSER's role (the coordinator), NOT
        // whichever expert ran last. Two traps, both seen in dogfood:
        //   • NOT d.inputTokens — for a gated / multi-expert turn that's the AGGREGATE input (Gate B sums
        //     implementer + verifier cumulative → run-stats `inTokens`, e.g. 10.99M), a billing total.
        //   • NOT the last assistant message's context — that message is the last DISPATCHED sub-expert (e.g.
        //     the Gate B verifier), whose agent-loop context (100K+ of files it read) is not the coordinator's
        //     window occupancy. Surfacing it made the meter jump to the sub-expert's size the instant a turn
        //     ended — the live onConvUsage path already keeps sub-steps out (BUG 1 there); this was the one
        //     place that re-introduced them on done.
        // Take the last COORDINATOR step's OWN context (its synthesis / direct turn). If the coordinator only
        // dispatched (intro is 0-context, no synthesis), leave the live-maintained value untouched.
        const lastCtx = [...msgs]
          .reverse()
          .find((m) => m.role === 'assistant' && m.expertId === 'coordinator' && typeof m.inputTokens === 'number' && m.inputTokens > 0)?.inputTokens
        return {
          byConversation: { ...s.byConversation, [meta.convId]: msgs },
          streaming: { ...s.streaming, [meta.convId]: false },
          contextTokens: typeof lastCtx === 'number' ? { ...s.contextTokens, [meta.convId]: lastCtx } : s.contextTokens
        }
      })
      void get().loadConversations() // bump title / updated_at
    })
    at.onError((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      coordinatorMeta.delete(d.streamId)
      if (meta) finishWithError(meta.convId, d.message)
    })
    // Agent-dispatched expert tool activity (doc 19 §11 phase 2). Unlike the agent path (one message per
    // loop turn), a coordinator STEP is ONE expertId-tagged message; the dispatched loop runs many turns,
    // so tool cards / servers / citations ACCUMULATE onto that message. All five locate it by walking back
    // to the streaming bubble whose expertId === roleId (parallel panels interleave — the last bubble
    // isn't always this role's), never finalizing it (step:done owns that).
    at.onToolStart((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m, tools: m.tools ? [...m.tools] : m.tools }))
        for (let i = msgs.length - 1; i >= 0; i--) {
          if (msgs[i].role === 'assistant' && msgs[i].streaming && msgs[i].expertId === d.roleId) {
            if (!msgs[i].tools?.some((t) => t.id === d.id)) {
              msgs[i].tools = [...(msgs[i].tools ?? []), { id: d.id, name: d.name, input: {}, status: 'running' as const }]
              msgs[i].blocks = [...(msgs[i].blocks ?? []), { kind: 'tool', id: d.id }] // slot the card into this step's ordered stream
            }
            break
          }
        }
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    at.onSubToolStart((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        let i = locateSubToolMsgIndex(msgs, d.roleId, d.parentToolId, d.toolUseId)
        // A sub-tool can arrive BEFORE this role's segment exists in the store: step:start and sub-tool:start
        // cross the main→renderer IPC as separate sends in separate ticks, so their order isn't guaranteed. The
        // flaky case is panel_examine's PanelExamine card (sentinel parent 'coordinator-gate-b' matches no card,
        // so it can only anchor on the role's latest message) — if its event wins the race it found no message
        // and was silently dropped (i<0), so the panel card never rendered. Don't drop it: open a streaming
        // bubble for the role and anchor the card there. A later step:start for the same role REUSES this bubble
        // (onStepStart matches expertId === roleId), so no duplicate segment.
        if (i < 0 && d.roleId) {
          msgs.push({ id: uid(), role: 'assistant', text: '', streaming: true, expertId: d.roleId })
          i = msgs.length - 1
        }
        if (i >= 0) msgs[i] = applySubToolStart(msgs[i], d.parentToolId, d.toolUseId, d.name, d.input)
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    at.onSubToolDone((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        let i = locateSubToolMsgIndex(msgs, d.roleId, d.parentToolId, d.toolUseId)
        // Same race guard as onSubToolStart: a done can be the FIRST event we see for a card whose start lost the
        // IPC race and landed nothing (or whose role segment isn't in the store yet). Ensure a bubble so the
        // resolved card still surfaces rather than vanishing.
        if (i < 0 && d.roleId) {
          msgs.push({ id: uid(), role: 'assistant', text: '', streaming: true, expertId: d.roleId })
          i = msgs.length - 1
        }
        if (i >= 0) msgs[i] = applySubToolDone(msgs[i], d.parentToolId, d.toolUseId, d.name, d.result, d.isError, d.input)
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    at.onSubToolDelta((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        const i = locateSubToolMsgIndex(msgs, d.roleId, d.parentToolId, d.toolUseId)
        if (i >= 0) msgs[i] = applySubToolDelta(msgs[i], d.parentToolId, d.toolUseId, d.delta)
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    // A collab expert entered (active=true) / left (active=false) a turn batch. Toggle a `parked` flag on its
    // single accumulating bubble so a PARKED expert (done its turn, waiting between turns) stops showing the
    // live "Thinking…" readout. The bubble stays streaming:true (a resume keeps appending to it via
    // appendDeltaToRole); only the readout visibility changes (chat-segment segStreaming excludes parked).
    at.onExpertActive((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        for (let i = msgs.length - 1; i >= 0; i--) {
          if (msgs[i].role === 'assistant' && msgs[i].expertId === d.roleId) {
            if (!!msgs[i].parked === d.active) msgs[i] = { ...msgs[i], parked: !d.active }
            break
          }
        }
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    at.onAssistant((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        for (let i = msgs.length - 1; i >= 0; i--) {
          const m = msgs[i]
          if (m.role === 'assistant' && m.streaming && m.expertId === d.roleId) {
            // Merge this turn's tool_use into the step's cards (fill authoritative name+input on the ones
            // onToolStart created; append any not yet seen). Do NOT set text — step:done is authoritative.
            const tools = [...(m.tools ?? [])]
            const blocks = [...(m.blocks ?? [])]
            for (const b of d.blocks) {
              if (b.type === 'tool_use') {
                const idx = tools.findIndex((t) => t.id === b.id)
                if (idx !== -1) tools[idx] = { ...tools[idx], name: b.name, input: b.input, subTools: tools[idx].subTools }
                else {
                  tools.push({ id: b.id, name: b.name, input: b.input, status: 'running' as const })
                  blocks.push({ kind: 'tool', id: b.id }) // a tool we hadn't seen via onToolStart → add to the order
                }
              }
            }
            m.tools = tools
            m.blocks = blocks
            const newServers = d.blocks
              .filter((b): b is { type: 'server'; serverType: string; query?: string; url?: string } => b.type === 'server' && SHOWN_SERVER_BLOCKS.has(b.serverType))
              .map((b) => ({ serverType: b.serverType, query: b.query, url: b.url }))
            if (newServers.length) m.servers = [...(m.servers ?? []), ...newServers]
            const seenCite = new Set((m.citations ?? []).map((c) => c.url))
            const textCites = d.blocks.flatMap((b) => (b.type === 'text' ? (b.citations ?? []) : []))
            const visited = d.blocks.flatMap((b) =>
              b.type === 'server' && b.serverType === 'web_search_call' && b.url ? [{ url: b.url }] : []
            )
            // prefer url citations; fall back to visited sites only when the message has no citations yet
            const src = textCites.length || (m.citations?.length ?? 0) > 0 ? textCites : visited
            const newCites = src.filter((c) => (seenCite.has(c.url) ? false : (seenCite.add(c.url), true)))
            if (newCites.length) m.citations = [...(m.citations ?? []), ...newCites]
            msgs[i] = m
            break
          }
        }
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    at.onResults((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m, tools: m.tools ? [...m.tools] : m.tools }))
        for (const r of d.results) {
          for (let i = msgs.length - 1; i >= 0; i--) {
            const idx = msgs[i].tools?.findIndex((t) => t.id === r.toolUseId && t.status === 'running') ?? -1
            if (idx !== -1 && msgs[i].tools) {
              msgs[i].tools![idx] = { ...msgs[i].tools![idx], status: r.isError ? 'error' : 'done', result: r.content }
              break
            }
          }
        }
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    at.onPermission((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => ({
        permission: { ...s.permission, [meta.convId]: { permissionId: d.permissionId, toolName: d.toolName, input: d.input, reason: d.reason, source: 'coordinator', roleId: d.roleId } }
      }))
    })
    at.onPermissionCancel((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      set((s) => (s.permission[meta.convId]?.permissionId === d.permissionId ? { permission: { ...s.permission, [meta.convId]: null } } : {}))
    })
    at.onApproval((d) => {
      const meta = coordinatorMeta.get(d.streamId)
      if (!meta) return
      const key = uid()
      set((s) => ({
        approvals: {
          ...s.approvals,
          [meta.convId]: [
            ...(s.approvals[meta.convId] ?? []),
            { key, roleId: d.roleId, zone: d.zone, toolName: d.toolName, reason: d.reason, pendingId: d.pendingId, status: 'open' as const }
          ]
        }
      }))
      // A yellow card is just an auto-approved note — surface it briefly, then fade it so notes don't pile
      // up and clutter the thread. Red cards stay until the user resolves them (they fade on approve/reject).
      if (d.zone === 'yellow') {
        setTimeout(() => set((s) => ({
          approvals: { ...s.approvals, [meta.convId]: (s.approvals[meta.convId] ?? []).filter((c) => c.key !== key) }
        })), 4000)
      }
    })

  }

  // Drop the trailing streaming placeholder + surface the error (shared by both paths).
  const finishWithError = (convId: string, message: string): void => {
    set((s) => {
      const msgs = (s.byConversation[convId] ?? []).filter((m) => !(m.role === 'assistant' && m.streaming))
      return {
        byConversation: { ...s.byConversation, [convId]: msgs },
        streaming: { ...s.streaming, [convId]: false },
        error: { ...s.error, [convId]: message },
        permission: { ...s.permission, [convId]: null }
      }
    })
  }

  return {
    conversations: [],
    activeConv: null,
    byConversation: {},
    streaming: {},
    error: {},
    permission: {},
    question: {},
    approvals: {},
    contextTokens: {},
    liveInput: {},
    liveOutput: {},
    liveCached: {},
    streamStartedAt: {},
    retry: {},

    loadConversations: async () => {
      set({ conversations: await window.api.conversations.list() })
    },

    openConversation: async (convId) => {
      set({ activeConv: convId })
      if (get().byConversation[convId]) return // already loaded
      // Load messages + (for agent conversations) rebuild tool cards from the transcript, keyed by run_id.
      const [rows, transcript] = await Promise.all([
        window.api.conversations.messages(convId),
        window.api.agent.transcript(convId)
      ])
      const mapped: ChatMessage[] = rows.map((m) => {
        const run = m.author !== 'user' && m.runId ? transcript[m.runId] : undefined
        // Rebuild the ordered text+tool stream so a reopened agent turn interleaves exactly like the live one.
        // The transcript's text blocks are what the persisted reply was assembled from, so they match m.content;
        // as a safety net, if the run ran tools but the rebuilt stream carries no text (pure tool turns), fold
        // the DB reply in as a trailing text block so the final answer is never dropped.
        let blocks: MsgBlock[] | undefined
        if (run?.tools.length) {
          blocks = run.blocks.length ? [...run.blocks] : []
          if (m.content.trim() && !blocks.some((b) => b.kind === 'text')) blocks.push({ kind: 'text', text: m.content })
        }
        return {
          id: m.id,
          role: m.author === 'user' ? 'user' : 'assistant',
          text: m.content,
          blocks,
          images: m.attachments.length ? m.attachments.map((a) => ({ url: a.url, name: a.name ?? 'image' })) : undefined,
          tools: run?.tools.length ? run.tools : undefined,
          servers: run?.servers.length ? run.servers : undefined,
          citations: run?.citations.length ? run.citations : undefined,
          expertId: m.author === 'user' ? null : m.expertId,
          dispatch: m.dispatch,
          segmentKind: m.author === 'user' ? null : m.segmentKind,
          inputTokens: m.author !== 'user' && m.inputTokens > 0 ? m.inputTokens : undefined,
          cacheReadTokens: m.author !== 'user' && m.cacheReadTokens > 0 ? m.cacheReadTokens : undefined,
          outputTokens: m.author !== 'user' && m.outputTokens > 0 ? m.outputTokens : undefined,
          sentTokens: m.author !== 'user' && m.sentTokens > 0 ? m.sentTokens : undefined
        }
      })
      // Seed the composer readout from the most recent assistant turn's measured prompt tokens.
      const lastCtx = [...rows].reverse().find((m) => m.author !== 'user' && m.inputTokens > 0)?.inputTokens
      set((s) => ({
        byConversation: { ...s.byConversation, [convId]: mapped },
        contextTokens: lastCtx ? { ...s.contextTokens, [convId]: lastCtx } : s.contextTokens
      }))
    },

    newConversation: () => set({ activeConv: null }),

    send: async ({ expertId, endpointId, model, thinking, text, images, cwd, contextWindow, permissionMode, imageModel }) => {
      ensureListeners()
      let convId = get().activeConv
      const isNew = !convId
      if (!convId) {
        if (creating) return // a create is already in flight for this fresh thread — drop the duplicate
        creating = true
        const title = text.trim().slice(0, 60) || 'New conversation'
        try {
          const conv = await window.api.conversations.create({ kind: 'single', primaryRoleId: expertId, title })
          convId = conv.id
          set((s) => ({ activeConv: conv.id, conversations: [conv, ...s.conversations] }))
        } catch {
          return // create failed; user can retry
        } finally {
          creating = false
        }
      }
      const cid = convId
      // Shared failure path for ALL three send routes (coordinator / agent / chat). The FIRST message of
      // a fresh conversation failing means nothing was persisted — roll the empty conversation back so it
      // doesn't linger title-less in History with a phantom user bubble. Established conversations keep
      // their history and surface the error on the streaming placeholder instead.
      const failSend = (e: unknown): void => {
        if (isNew) {
          void window.api.conversations.remove(cid).catch(() => {})
          set((s) => {
            const byConv = { ...s.byConversation }
            delete byConv[cid]
            return {
              conversations: s.conversations.filter((c) => c.id !== cid),
              byConversation: byConv,
              streaming: { ...s.streaming, [cid]: false },
              activeConv: s.activeConv === cid ? null : s.activeConv
            }
          })
        } else {
          finishWithError(cid, e instanceof Error ? e.message : String(e))
        }
      }
      const userImages = (images ?? []).map((i) => ({ url: i.dataUrl, name: i.name }))

      // Optimistic render FIRST (no empty-state flash). The streaming assistant placeholder fills in via
      // the path's delta/done events.
      set((s) => {
        const prev = s.byConversation[cid] ?? []
        return {
          byConversation: {
            ...s.byConversation,
            [cid]: [
              ...prev,
              { id: uid(), role: 'user', text, images: userImages.length ? userImages : undefined },
              { id: uid(), role: 'assistant', text: '', streaming: true }
            ]
          },
          streaming: { ...s.streaming, [cid]: true },
          streamStartedAt: { ...s.streamStartedAt, [cid]: Date.now() },
          // Reset only the current live overlay for the new turn so it doesn't briefly show stale usage before
          // the first live ping lands. Session totals stay intact and advance only on turn-final events.
          // contextTokens is left intact — it's the current-context seed for the "/ window" indicator and is
          // overwritten by the turn's own count.
          liveInput: { ...s.liveInput, [cid]: 0 },
          liveOutput: { ...s.liveOutput, [cid]: 0 },
          liveCached: { ...s.liveCached, [cid]: 0 },
          error: { ...s.error, [cid]: null }
        }
      })
      if (isNew) {
        void window.api.conversations
          .title({ convId: cid, firstMessage: text.slice(0, 1000), endpointId, model })
          .then((title) => {
            if (title) set((s) => ({ conversations: s.conversations.map((c) => (c.id === cid ? { ...c, title } : c)) }))
          })
          .catch(() => {})
      }

      if (roleIsCoordinator(expertId)) {
        // Coordinator path: renderer persists the user turn (chat-path style), then coordinator.run does the route
        // → dispatch → (optional) synthesize. coordinator.service reads the just-persisted user message + any
        // attachments straight from the conversation history; we don't re-ship images over IPC.
        try {
          await window.api.conversations.append(cid, {
            author: 'user',
            expertId,
            content: text,
            attachments: userImages.map((i) => ({ url: i.url, name: i.name }))
          })
          // cwdByRole = every expert's working dir (the workspace store's cwdByExpert). A dispatched agent
          // expert runs in cwdByRole[its roleId]; coordinator's own cwd is irrelevant (it never runs tools).
          // cwdByRole + modeByRole = every expert's working dir + permission mode (workspace store). A
          // dispatched / collab expert honors its own mode (bypass = full auto) instead of being forced to
          // 'default' — previously omitted, so coordinator-routed work ignored the user's bypass selection.
          const ws = useWorkspace.getState()
          const { streamId } = await window.api.coordinator.run({ convId: cid, prompt: text, cwdByRole: ws.cwdByExpert, modeByRole: ws.modeByExpert })
          coordinatorMeta.set(streamId, { convId: cid, endpointId, model })
        } catch (e) {
          failSend(e)
        }
        return
      }

      if (roleHasAgent(expertId)) {
        // Agent path: the backend persists the user turn + final reply itself; we don't append here.
        // imageModel rides along for designer (Georgia) — the backend hands it to ns_generate_image; the
        // tool itself is gated server-side by the Tools setting, so no enabled-check is needed here.
        try {
          const { streamId } = await window.api.agent.run({
            convId: cid,
            endpointId,
            model,
            prompt: text,
            cwd: cwd ?? '',
            roleId: expertId,
            permissionMode,
            thinking,
            contextWindow,
            imageModel,
            images: images?.map((i) => ({ dataUrl: i.dataUrl, mime: i.mime }))
          })
          agentMeta.set(streamId, { convId: cid, expertId, endpointId, model })
        } catch (e) {
          failSend(e)
        }
        return
      }

      // Chat path: persist the user turn (backend reads it from the DB to assemble context), then send.
      // System prompt: custom roles use their user-defined systemPrompt field (from custom_roles);
      // built-ins fall back to a brief identity built from STUDIO_DATA. An empty system prompt is the
      // last-resort fallback (the LLM still gets the user message, just without identity priming).
      const custom = useCustomRoles.getState().list.find((r) => r.id === expertId)
      let systemPrompt = ''
      if (custom) {
        systemPrompt = custom.systemPrompt?.trim() || `You are ${custom.name}, a user-defined expert.`
      } else {
        const expert = STUDIO_DATA.EXPERT_BY_ID[expertId]
        if (expert) systemPrompt = `You are ${expert.name}, ${expert.specialty.toLowerCase()}. ${expert.personality}.`
      }
      try {
        await window.api.conversations.append(cid, {
          author: 'user',
          expertId,
          content: text,
          attachments: userImages.map((i) => ({ url: i.url, name: i.name }))
        })
        const { streamId } = await window.api.chat.send({ convId: cid, roleId: expertId, endpointId, model, systemPrompt, thinking })
        streamMeta.set(streamId, { convId: cid, expertId, endpointId, model })
      } catch (e) {
        failSend(e)
      }
    },

    stop: () => {
      const cid = get().activeConv
      if (!cid) return
      for (const [sid, meta] of streamMeta) {
        if (meta.convId === cid) {
          void window.api.chat.stop(sid)
          streamMeta.delete(sid)
        }
      }
      for (const [sid, meta] of agentMeta) {
        if (meta.convId === cid) {
          void window.api.agent.stop(sid)
          agentMeta.delete(sid)
        }
      }
      for (const [sid, meta] of coordinatorMeta) {
        if (meta.convId === cid) {
          void window.api.coordinator.stop(sid)
          coordinatorMeta.delete(sid)
        }
      }
      // stop() deleted the meta above, so the backend's terminal done/error/cancel events will meta-miss and
      // SKIP their normal cleanup. So we finalize everything HERE, or it never happens:
      //  - close out EVERY in-flight assistant bubble (parallel/council stream several at once) — a message
      //    left `streaming:true`, or a tool left `status:'running'`, keeps ThinkingReadout's 250ms clock
      //    ticking forever ("still counting tokens / time after stop").
      //  - drop a trailing empty placeholder (stopped before any output) so there's no blank bubble.
      //  - clear any pending approval/question dialog (same meta-miss reason).
      set((s) => {
        const msgs = (s.byConversation[cid] ?? []).map((m) => {
          if (m.role !== 'assistant' || !m.streaming) return m
          const tools = m.tools?.some((t) => t.status === 'running')
            ? m.tools.map((t) => (t.status === 'running' ? { ...t, status: 'error' as const } : t))
            : m.tools
          return { ...m, streaming: false, tools }
        })
        const tail = msgs[msgs.length - 1]
        const cleaned =
          tail && tail.role === 'assistant' && !tail.text.trim() && !tail.images?.length && !tail.tools?.length
            ? msgs.slice(0, -1)
            : msgs
        return {
          byConversation: { ...s.byConversation, [cid]: cleaned },
          streaming: { ...s.streaming, [cid]: false },
          permission: { ...s.permission, [cid]: null },
          question: { ...s.question, [cid]: null },
          approvals: { ...s.approvals, [cid]: [] } // drop stale coordinator approval cards from the killed run
        }
      })
    },

    respondPermission: (convId, allow) => {
      const p = get().permission[convId]
      if (!p) return
      const resp = { permissionId: p.permissionId, allow }
      // Route to whichever backend raised it — a coordinator-dispatched expert's prompt lives in a separate
      // pending map than a direct agent run's (see coordinator.handler / agent.handler).
      if (p.source === 'coordinator') void window.api.coordinator.respondPermission(resp)
      else void window.api.agent.respondPermission(resp)
      set((s) => ({ permission: { ...s.permission, [convId]: null } }))
    },

    respondQuestion: (convId, answer) => {
      const q = get().question[convId]
      if (!q) return
      void window.api.agent.respondQuestion({ questionId: q.questionId, answer })
      set((s) => ({ question: { ...s.question, [convId]: null } }))
    },

    approveApproval: async (convId, pendingId) => {
      const patch =
        (status: ApprovalCard['status'], result?: string) =>
        (s: ChatState): Partial<ChatState> => ({
          approvals: { ...s.approvals, [convId]: (s.approvals[convId] ?? []).map((c) => (c.pendingId === pendingId ? { ...c, status, result } : c)) }
        })
      set(patch('executing'))
      const res = await window.api.approval.approve(pendingId)
      set(patch(res.ok ? 'approved' : 'failed', res.output))
      // Once it has run, the card is noise — fade it from the thread after a beat (keep failures; their
      // error output is worth leaving up).
      if (res.ok) {
        setTimeout(() => set((s) => ({
          approvals: { ...s.approvals, [convId]: (s.approvals[convId] ?? []).filter((c) => c.pendingId !== pendingId) }
        })), 2500)
      }
    },

    rejectApproval: (convId, pendingId) => {
      void window.api.approval.reject(pendingId)
      set((s) => ({
        approvals: { ...s.approvals, [convId]: (s.approvals[convId] ?? []).map((c) => (c.pendingId === pendingId ? { ...c, status: 'rejected' as const } : c)) }
      }))
      setTimeout(() => set((s) => ({
        approvals: { ...s.approvals, [convId]: (s.approvals[convId] ?? []).filter((c) => c.pendingId !== pendingId) }
      })), 2500)
    },

    removeConversation: async (convId) => {
      await window.api.conversations.remove(convId)
      set((s) => {
        const byConv = { ...s.byConversation }
        delete byConv[convId]
        return {
          conversations: s.conversations.filter((c) => c.id !== convId),
          byConversation: byConv,
          activeConv: s.activeConv === convId ? null : s.activeConv
        }
      })
    },

    rename: async (convId, title) => {
      await window.api.conversations.rename(convId, title)
      set((s) => ({ conversations: s.conversations.map((c) => (c.id === convId ? { ...c, title } : c)) }))
    },

    setPinned: async (convId, pinned) => {
      await window.api.conversations.pin(convId, pinned)
      set((s) => ({ conversations: s.conversations.map((c) => (c.id === convId ? { ...c, pinned } : c)) }))
    },

    setArchived: async (convId, archived) => {
      await window.api.conversations.archive(convId, archived)
      set((s) => ({ conversations: s.conversations.map((c) => (c.id === convId ? { ...c, archived } : c)) }))
    }
  }
})
