import { create } from 'zustand'
import { STUDIO_DATA } from '@/data/studio-data'
import type { EffortLevel } from '@/lib/thinking'

// Unified per-conversation chat store (L3). A conversation is a real DB row; messages persist to the
// messages table. Every role is a chat; a role whose id is in AGENT_ROLES has its replies generated by
// the agent (tool use over agent:* IPC) instead of plain text streaming (chat:* IPC). The store routes
// the send + accumulates both event streams into the same byConversation message list — agent turns
// additionally carry tool cards + may raise a permission prompt.

type ConversationDto = Awaited<ReturnType<typeof window.api.conversations.list>>[number]

// Roles whose replies come from the agent (tool use). This version: Hex only. Add ids as more roles
// get an agent.
const AGENT_ROLES = new Set(['hex'])
export const roleHasAgent = (expertId: string): boolean => AGENT_ROLES.has(expertId)

export interface ToolCall {
  id: string
  name: string
  input: unknown
  status: 'running' | 'done' | 'error'
  result?: string
}
export interface ChatMessage {
  id: string
  role: 'user' | 'assistant'
  text: string
  images?: { url: string; name: string }[]
  tools?: ToolCall[] // present on agent (tool-using) turns
  streaming?: boolean
}
export interface PermissionPrompt {
  permissionId: string
  toolName: string
  input: unknown
  reason?: string
}

interface SendOpts {
  expertId: string
  endpointId: string
  model: string
  thinking?: { effort?: EffortLevel; budgetTokens?: number }
  text: string
  images?: { dataUrl: string; mime: string; name: string }[]
  cwd?: string // the project dir — required for agent roles, ignored for plain chat
  contextWindow?: number // agent roles pass the model's context window (drives compaction)
}

interface ChatState {
  conversations: ConversationDto[]
  activeConv: string | null
  byConversation: Record<string, ChatMessage[]>
  streaming: Record<string, boolean>
  error: Record<string, string | null>
  permission: Record<string, PermissionPrompt | null> // per-conversation (future: parallel agent runs)
  contextTokens: Record<string, number> // per-conversation exact prompt tokens of the last sent turn
  loadConversations: () => Promise<void>
  openConversation: (convId: string) => Promise<void>
  newConversation: () => void
  send: (opts: SendOpts) => Promise<void>
  stop: () => void
  respondPermission: (convId: string, allow: boolean) => void
  removeConversation: (convId: string) => Promise<void>
  rename: (convId: string, title: string) => Promise<void>
}

const uid = (): string => globalThis.crypto.randomUUID()
type Meta = { convId: string; expertId: string; endpointId: string; model: string }
const streamMeta = new Map<string, Meta>() // chat (plain text) path: streamId → conversation
const agentMeta = new Map<string, Meta>() // agent (tool use) path: streamId → conversation
let creating = false // sync guard: blocks a double-create when a fresh thread's first message fires twice
let listening = false

export const useChat = create<ChatState>((set, get) => {
  // Append a text delta to the last streaming assistant message; start a fresh one if the last isn't
  // streaming. Agent turns are multi-step (assistant → tool results → assistant …) so each new turn
  // becomes its own message, leaving the prior turn's text + tool cards intact.
  const appendDelta = (convId: string, text: string): void => {
    set((s) => {
      const msgs = (s.byConversation[convId] ?? []).map((m) => ({ ...m }))
      let cur = msgs[msgs.length - 1]
      if (!cur || cur.role !== 'assistant' || !cur.streaming) {
        cur = { id: uid(), role: 'assistant', text: '', streaming: true }
        msgs.push(cur)
      }
      cur.text += text
      return { byConversation: { ...s.byConversation, [convId]: msgs } }
    })
  }

  const ensureListeners = (): void => {
    if (listening) return
    listening = true

    // ---- chat (plain text) path: chat:delta / chat:done / chat:error ----
    const api = window.api.chat
    api.onDelta((d) => {
      const meta = streamMeta.get(d.streamId)
      if (meta) appendDelta(meta.convId, d.text)
    })
    api.onDone((d) => {
      const meta = streamMeta.get(d.streamId)
      streamMeta.delete(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        const cur = msgs[msgs.length - 1]
        if (cur && cur.role === 'assistant') {
          cur.streaming = false
          cur.text = d.text // done is authoritative
        }
        return {
          byConversation: { ...s.byConversation, [meta.convId]: msgs },
          streaming: { ...s.streaming, [meta.convId]: false }
        }
      })
      const ctxTok = d.inputTokens
      if (typeof ctxTok === 'number')
        set((s) => ({ contextTokens: { ...s.contextTokens, [meta.convId]: ctxTok } }))
      void window.api.conversations
        .append(meta.convId, { author: 'expert', expertId: meta.expertId, model: meta.model, content: d.text, inputTokens: ctxTok })
        .then(() => get().loadConversations())
      void window.api.memory.onTurn({ convId: meta.convId, roleId: meta.expertId, endpointId: meta.endpointId, model: meta.model })
      void window.api.chat.compress({ convId: meta.convId, roleId: meta.expertId, endpointId: meta.endpointId, model: meta.model, currentTokens: ctxTok })
    })
    api.onError((d) => {
      const meta = streamMeta.get(d.streamId)
      streamMeta.delete(d.streamId)
      if (meta) finishWithError(meta.convId, d.message)
    })

    // ---- agent (tool use) path: agent:delta / assistant / results / permission / done / error ----
    // The backend persists the user + final assistant turn itself; here we only accumulate the live UI
    // (text + tool cards) and the permission prompt. We never re-append the assistant message.
    const ag = window.api.agent
    ag.onDelta((d) => {
      const meta = agentMeta.get(d.streamId)
      if (meta) appendDelta(meta.convId, d.text)
    })
    ag.onAssistant((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        let cur = msgs[msgs.length - 1]
        if (!cur || cur.role !== 'assistant' || !cur.streaming) {
          cur = { id: uid(), role: 'assistant', text: '', streaming: true }
          msgs.push(cur)
        }
        cur.text = d.blocks
          .filter((b): b is { type: 'text'; text: string } => b.type === 'text')
          .map((b) => b.text)
          .join('') // onAssistant is authoritative for the turn's text (deltas were a preview)
        cur.tools = d.blocks
          .filter((b): b is { type: 'tool_use'; id: string; name: string; input: unknown } => b.type === 'tool_use')
          .map((b) => ({ id: b.id, name: b.name, input: b.input, status: 'running' as const }))
        cur.streaming = false // turn complete; the next turn (after results) starts a new message
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    ag.onResults((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m, tools: m.tools ? [...m.tools] : m.tools }))
        for (const r of d.results) {
          // apply to the most recent message holding a still-running tool with that id
          for (let i = msgs.length - 1; i >= 0; i--) {
            const idx = msgs[i].tools?.findIndex((t) => t.id === r.toolUseId && t.status === 'running') ?? -1
            if (idx !== -1 && msgs[i].tools) {
              msgs[i].tools![idx] = { ...msgs[i].tools![idx], status: r.isError ? 'error' : 'done', result: r.content }
              break
            }
          }
        }
        return { byConversation: { ...s.byConversation, [meta.convId]: msgs } }
      })
    })
    ag.onPermission((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => ({
        permission: { ...s.permission, [meta.convId]: { permissionId: d.permissionId, toolName: d.toolName, input: d.input, reason: d.reason } }
      }))
    })
    ag.onPermissionCancel((d) => {
      const meta = agentMeta.get(d.streamId)
      if (!meta) return
      set((s) => (s.permission[meta.convId]?.permissionId === d.permissionId ? { permission: { ...s.permission, [meta.convId]: null } } : {}))
    })
    ag.onDone((d) => {
      const meta = agentMeta.get(d.streamId)
      agentMeta.delete(d.streamId)
      if (!meta) return
      set((s) => {
        const msgs = (s.byConversation[meta.convId] ?? []).map((m) => ({ ...m }))
        const cur = msgs[msgs.length - 1]
        if (cur && cur.role === 'assistant') cur.streaming = false
        return {
          byConversation: { ...s.byConversation, [meta.convId]: msgs },
          streaming: { ...s.streaming, [meta.convId]: false },
          permission: { ...s.permission, [meta.convId]: null },
          contextTokens:
            typeof d.inputTokens === 'number'
              ? { ...s.contextTokens, [meta.convId]: d.inputTokens }
              : s.contextTokens
        }
      })
      void get().loadConversations() // backend persisted the final reply + maybe a title
    })
    ag.onError((d) => {
      const meta = agentMeta.get(d.streamId)
      agentMeta.delete(d.streamId)
      if (meta) finishWithError(meta.convId, d.message)
    })
  }

  // Drop the trailing streaming placeholder + surface the error (shared by both paths).
  const finishWithError = (convId: string, message: string): void => {
    set((s) => {
      const msgs = (s.byConversation[convId] ?? []).filter((m) => !(m.role === 'assistant' && m.streaming))
      return {
        byConversation: { ...s.byConversation, [convId]: msgs },
        streaming: { ...s.streaming, [convId]: false },
        error: { ...s.error, [convId]: message },
        permission: { ...s.permission, [convId]: null }
      }
    })
  }

  return {
    conversations: [],
    activeConv: null,
    byConversation: {},
    streaming: {},
    error: {},
    permission: {},
    contextTokens: {},

    loadConversations: async () => {
      set({ conversations: await window.api.conversations.list() })
    },

    openConversation: async (convId) => {
      set({ activeConv: convId })
      if (get().byConversation[convId]) return // already loaded
      // Load messages + (for agent conversations) rebuild tool cards from the transcript, keyed by run_id.
      const [rows, tools] = await Promise.all([
        window.api.conversations.messages(convId),
        window.api.agent.transcript(convId)
      ])
      const mapped: ChatMessage[] = rows.map((m) => ({
        id: m.id,
        role: m.author === 'user' ? 'user' : 'assistant',
        text: m.content,
        images: m.attachments.length ? m.attachments.map((a) => ({ url: a.url, name: a.name ?? 'image' })) : undefined,
        tools: m.author !== 'user' && m.runId && tools[m.runId]?.length ? tools[m.runId] : undefined
      }))
      // Seed the composer readout from the most recent assistant turn's measured prompt tokens.
      const lastCtx = [...rows].reverse().find((m) => m.author !== 'user' && m.inputTokens > 0)?.inputTokens
      set((s) => ({
        byConversation: { ...s.byConversation, [convId]: mapped },
        contextTokens: lastCtx ? { ...s.contextTokens, [convId]: lastCtx } : s.contextTokens
      }))
    },

    newConversation: () => set({ activeConv: null }),

    send: async ({ expertId, endpointId, model, thinking, text, images, cwd, contextWindow }) => {
      ensureListeners()
      let convId = get().activeConv
      const isNew = !convId
      if (!convId) {
        if (creating) return // a create is already in flight for this fresh thread — drop the duplicate
        creating = true
        const title = text.trim().slice(0, 60) || 'New conversation'
        try {
          const conv = await window.api.conversations.create({ kind: 'single', primaryRoleId: expertId, title })
          convId = conv.id
          set((s) => ({ activeConv: conv.id, conversations: [conv, ...s.conversations] }))
        } catch {
          return // create failed; user can retry
        } finally {
          creating = false
        }
      }
      const cid = convId
      const userImages = (images ?? []).map((i) => ({ url: i.dataUrl, name: i.name }))

      // Optimistic render FIRST (no empty-state flash). The streaming assistant placeholder fills in via
      // the path's delta/done events.
      set((s) => {
        const prev = s.byConversation[cid] ?? []
        return {
          byConversation: {
            ...s.byConversation,
            [cid]: [
              ...prev,
              { id: uid(), role: 'user', text, images: userImages.length ? userImages : undefined },
              { id: uid(), role: 'assistant', text: '', streaming: true }
            ]
          },
          streaming: { ...s.streaming, [cid]: true },
          error: { ...s.error, [cid]: null }
        }
      })
      if (isNew) {
        void window.api.conversations
          .title({ convId: cid, firstMessage: text.slice(0, 1000), endpointId, model })
          .then((title) => {
            if (title) set((s) => ({ conversations: s.conversations.map((c) => (c.id === cid ? { ...c, title } : c)) }))
          })
          .catch(() => {})
      }

      if (roleHasAgent(expertId)) {
        // Agent path: the backend persists the user turn + final reply itself; we don't append here.
        try {
          const { streamId } = await window.api.agent.run({
            convId: cid,
            endpointId,
            model,
            prompt: text,
            cwd: cwd ?? '',
            thinking,
            contextWindow,
            images: images?.map((i) => ({ dataUrl: i.dataUrl, mime: i.mime }))
          })
          agentMeta.set(streamId, { convId: cid, expertId, endpointId, model })
        } catch (e) {
          if (isNew) {
            // First agent run of a fresh conversation failed before the backend persisted anything —
            // roll back the empty conversation so it doesn't linger title-less with a phantom user bubble.
            void window.api.conversations.remove(cid).catch(() => {})
            set((s) => {
              const byConv = { ...s.byConversation }
              delete byConv[cid]
              return {
                conversations: s.conversations.filter((c) => c.id !== cid),
                byConversation: byConv,
                streaming: { ...s.streaming, [cid]: false },
                activeConv: s.activeConv === cid ? null : s.activeConv
              }
            })
          } else {
            finishWithError(cid, e instanceof Error ? e.message : String(e))
          }
        }
        return
      }

      // Chat path: persist the user turn (backend reads it from the DB to assemble context), then send.
      const expert = STUDIO_DATA.EXPERT_BY_ID[expertId]
      const systemPrompt = expert
        ? `You are ${expert.name}, ${expert.specialty.toLowerCase()}. ${expert.personality}.`
        : ''
      try {
        await window.api.conversations.append(cid, {
          author: 'user',
          expertId,
          content: text,
          attachments: userImages.map((i) => ({ url: i.url, name: i.name }))
        })
        const { streamId } = await window.api.chat.send({ convId: cid, roleId: expertId, endpointId, model, systemPrompt, thinking })
        streamMeta.set(streamId, { convId: cid, expertId, endpointId, model })
      } catch (e) {
        finishWithError(cid, e instanceof Error ? e.message : String(e))
      }
    },

    stop: () => {
      const cid = get().activeConv
      if (!cid) return
      for (const [sid, meta] of streamMeta) {
        if (meta.convId === cid) {
          void window.api.chat.stop(sid)
          streamMeta.delete(sid)
        }
      }
      for (const [sid, meta] of agentMeta) {
        if (meta.convId === cid) {
          void window.api.agent.stop(sid)
          agentMeta.delete(sid)
        }
      }
      // Also clear any pending approval: stop just deleted the agentMeta, so the backend's done/cancel
      // events would meta-miss and leave the ApprovalDialog stuck on screen otherwise.
      set((s) => ({ streaming: { ...s.streaming, [cid]: false }, permission: { ...s.permission, [cid]: null } }))
    },

    respondPermission: (convId, allow) => {
      const p = get().permission[convId]
      if (!p) return
      void window.api.agent.respondPermission({ permissionId: p.permissionId, allow })
      set((s) => ({ permission: { ...s.permission, [convId]: null } }))
    },

    removeConversation: async (convId) => {
      await window.api.conversations.remove(convId)
      set((s) => {
        const byConv = { ...s.byConversation }
        delete byConv[convId]
        return {
          conversations: s.conversations.filter((c) => c.id !== convId),
          byConversation: byConv,
          activeConv: s.activeConv === convId ? null : s.activeConv
        }
      })
    },

    rename: async (convId, title) => {
      await window.api.conversations.rename(convId, title)
      set((s) => ({ conversations: s.conversations.map((c) => (c.id === convId ? { ...c, title } : c)) }))
    }
  }
})
