// @generated from Claude Desktop 1.17377.2 (app.asar .vite/build/index.js), CC visualize/"Imagine" asset `Wct`.
// Byte-identical to CC — do not edit. Spec: docs/visualize-alignment-design.md §3; archive: docs/visualize-assets/cds-tokens.md.js-escaped

export const cdsTokens = `<!-- @generated by apps/cds-docs/scripts/gen-cds-skill.mjs from packages/cds/{CLAUDE.md,docs/**}. Do not edit by hand — edit the source docs and re-run \`yarn workspace @ant/cds-docs gen:cds-skill\`. -->

# CDS tokens — vanilla

The Claude Design System token vocabulary for plain HTML/CSS/SVG
surfaces without React or Tailwind. Tokens are unprefixed CSS custom
properties (\`--text-primary\`, \`--surface-1\`, \`--border\`) declared on
\`:root\` by \`@ant/cds/tokens.vanilla.css\`, with dark-mode overrides under
\`[data-mode="dark"]\` and \`@media (prefers-color-scheme: dark)\`.

References below to \`CdsRoot\`, \`Button\`, or Tailwind utilities belong to
the React build; in vanilla, read a utility like \`bg-surface-1\` as the
underlying \`var(--surface-1)\`.

## Rules

### Token rule

Reference purpose-layer tokens as CSS custom properties:

\`\`\`css
/* GOOD */
background: var(--surface-1);
color: var(--text-secondary);
border: 0.5px solid var(--border);

/* BAD — raw hex, invisible in dark mode */
color: #3d3d3a;
\`\`\`

| Property   | Tokens |
| ---------- | ------ |
| Background | \`--surface-{0..3,popover,panel}\` · \`--bg-{accent,danger,success,warning,pro,neutral}\` · \`--fill-{role}\` |
| Text       | \`--text-{primary,secondary,muted,disabled}\` · \`--text-{accent,danger,success,warning,pro}\` · \`--on-{role}\` |
| Border     | \`--border\` (default hairline) · \`--border-{strong,stronger}\` · \`--border-{role}\` |
| Sizing     | \`--h-control\` · \`--pad-{sm,md,lg,xl}\` · \`--gap-{xs,sm,md,lg,xl}\` · \`--radius\` |
| Typography | \`--font-{sans,mono,voice}\` · \`--font-size-{caption,footnote,body,code,heading,title}\` |
| Shadow     | \`--shadow-{sm,md,lg,popover}\` |
| Motion     | \`--dur-{fast,snap,base,slow}\` · \`--ease-{out,snap,overshoot}\` |

### Dark mode rule

Dark mode is \`[data-mode="dark"]\` on \`:root\` (or \`prefers-color-scheme: dark\` with no explicit \`data-mode\`). All tokens flip automatically — never hardcode a dark-mode override.

### Muted text rule

Secondary copy uses \`color: var(--text-muted)\`, **never** \`opacity\` — opacity multiplies against the background and drifts per-surface.

### Accent rule

At most **one** accent-filled (\`variant="primary"\`) Button per view; siblings use \`secondary\` or \`ghost\`. The \`brand\` (clay) role is reserved for Claude-initiated actions — send, generate — never ordinary user CTAs.

### Restraint rule

Default to the quieter, lighter option — "too cluttered" is the most common design note.

- \`secondary\` is the default Button; \`primary\` / \`brand\` read as aggressive — don't reach for them in popovers, banners, or dense tool/canvas surfaces.
- Avoid disabled buttons. Keep them enabled and respond on use (disabled controls are low-contrast and show no tooltip on touch); use \`disabledReason\` only when you genuinely must disable.
- Dense lists: bordered rows, not rounded-rect cards.
- Don't oversize padding, tooltips, or badges — trust the density scale.

### Elevation rule

\`surface-0\` is the page canvas (via \`--page-bg\`); \`1\`/\`2\`/\`3\` step above it. At most **two** floating elevations (\`panel\` / \`popover\`) on screen at once. A third floating layer means \`Dialog\`, not popover-on-popover. Flat in-flow tiles (\`rounded-card bg-surface-1 shadow-card-ring\`) have no depth and don't count toward this limit.

---

## CDS principles

How something feels like Claude — the philosophy behind the tokens. Tokens tell you _what_ you can use; the [Rules](../CLAUDE.md#rules) tell you _how_ to apply them. These principles tell you _why_.

## Claude-native

cds is designed to be authored _by_ Claude as much as _for_ Claude's products. The \`CLAUDE.md\` you're reading is the system prompt; component docs are structured for retrieval; utilities are named so a model can guess them; the GenerateDemo page proves the loop works. A design system an LLM can use fluently is one humans can use fluently too.

## Clay is Claude's color

\`brand\` (clay) is reserved for what Claude does — send, generate, the spark mark. User-driven primary actions take the neutral \`accent\` blue; everything else stays gray. Holding clay back to a single role is what lets it carry meaning instead of becoming wallpaper.

## Serif is Claude's voice

Claude's responses render in serif; the surrounding chrome stays sans. Typography signals who's speaking before a word is read. cds ships \`--font-voice\` (the \`font-voice\` utility) for response surfaces.

## Density adapts to the surface

Console, claude.ai and antfarm share the same components — \`compact\` for dev tools and power users, \`comfortable\` for consumer apps. Density is one switch on \`CdsRoot\`, not a per-component prop, so a product can change its feel without forking a single component.

## Built to be extended

Every component takes \`className\`, every token is a public CSS var, and compound parts (\`.Root\`, \`.Item\`, \`.Trigger\`) sit under the porcelain helpers. The system expects you to compose past it — wrap, restyle, slot arbitrary children — not fork it.

## Restraint over options

One accent per view, one elevation step, t-shirt sizes instead of 0–12 scales. Fewer decisions at the call site means fewer ways for two screens to drift apart — consistency comes from removing knobs, not policing them.

## CDS tokens

Every visual decision in \`@ant/cds\` resolves to a \`--*\` CSS custom property. The TypeScript source of truth lives under \`packages/cds/tokens/\`; \`yarn gen:tokens\` emits the shipped CSS at [\`src/generated/tokens.css\`](../src/generated/tokens.css). Tokens are layered so that a single edit at the bottom (a hex value) propagates through ramps, roles, and purposes without touching component code.

## The layer model

\`\`\`
1. Base palette   --{hue}-{stop}      literal hex, mode-stable (gray, red, orange,
                                          yellow, green, aqua, blue, violet, magenta)
2. Theme ramps    --neutral-N         gray-N in light, gray-(900-N) in dark
                  --alpha-N           neutral-900 @ fixed opacity (so it flips too)
3. Elevation      --surface-{0..3}    0 = darkest, 3 = lightest, in BOTH modes
4. Purpose        --surface-{popover, what components actually consume; includes the
                   panel}, --text-*,  role mappings ({fill|bg|border|text}-{role})
                   --fill-*, --on-*
—  page-bg        --page-bg           hook the host app sets to its canvas color
5. Density        --h-control*,       px values; remapped by [data-density]
                   --pad-*, --gap-*,
                   --radius, --font-size-*,
                   --leading-*
6. Motion         --dur-*,            durations + easing curves (mode/density-invariant)
                   --ease-*
\`\`\`

**Components only read layer 4 (and 5 for sizing).** Layers 1–3 are wiring.

---

## 1. Base palette

Literal hex values, mode-stable — \`gray-500\` is the same pixel in light and dark. Nine hues share one 36-stop grid (0, 10–100 by 10, 150–800 by 50, 810–900 by 10); every hue anchors 0 = \`#ffffff\` and 900 = \`#0b0b0b\`. Rarely referenced directly — reach for layers 2–4 and let them resolve here.

---

## 2. Theme ramps

\`--neutral-N\` is \`gray-N\` in light and \`gray-(900-N)\` in dark, so \`neutral-0\` is always the near-background end and \`neutral-900\` the near-foreground end. Use it for "contrast against the page" (text, borders, fills); use \`gray-*\` when you mean a specific pixel value regardless of mode. \`--alpha-N\` is \`neutral-900\` at fixed opacity — a black wash in light, a white wash in dark, without per-mode overrides.

---

## 3. Elevation

| Token             | Light     | Dark       | Use case     |
| ----------------- | --------- | ---------- | ------------ |
| \`--surface-0\` | \`gray-20\` | \`gray-890\` | Page         |
| \`--surface-1\` | \`gray-10\` | \`gray-830\` | In-flow card |
| \`--surface-2\` | \`gray-0\`  | \`gray-750\` | Panel        |
| \`--surface-3\` | \`gray-0\`  | \`gray-700\` | Popover      |

The ordinal is absolute lightness in both modes: 0 is the darkest, 3 the lightest. \`--surface-panel\` and \`--surface-popover\` alias levels 2 and 3. The page canvas is the app's own choice — set \`--page-bg\` so knockout hairlines (focus ring inset, Pulse halo) blend into it; it defaults to \`surface-0\`.

---

## 4. Purpose

**This is the layer components consume.**

### Roles

Each role maps a semantic meaning to a hue. Property-first pattern: \`--fill-{role}\` (solid hue-450), \`--fill-{role}-hover\` (hue-400), \`--bg-{role}\` (hue-100 / dark hue-800), \`--border-{role}\` (solid hue-250 in light / hue-700 in dark), \`--text-{role}\` (600 fg). Warning's fill diverges: yellow-200 / hover yellow-250. Brand uses named \`clay-emphasized\` / hover \`clay\` (not hue stops).

| Role      | Hue    | Tokens                                                                                          |
| --------- | ------ | ----------------------------------------------------------------------------------------------- |
| \`accent\`  | blue   | \`--fill-accent{,-hover}\`, \`--bg-accent\`, \`--border-accent\`, \`--text-accent\`     |
| \`brand\`   | clay   | \`--fill-brand{,-hover}\`, \`--on-brand\` (fill-only — no text/bg/border)                   |
| \`danger\`  | red    | \`--fill-danger{,-hover}\`, \`--bg-danger\`, \`--border-danger\`, \`--text-danger\`     |
| \`success\` | green  | \`--fill-success{,-hover}\`, \`--bg-success\`, \`--border-success\`, \`--text-success\` |
| \`warning\` | yellow | \`--fill-warning{,-hover}\`, \`--bg-warning\`, \`--border-warning\`, \`--text-warning\` |
| \`pro\`     | purple | \`--fill-pro{,-hover}\`, \`--bg-pro\`, \`--border-pro\`, \`--text-pro\`                 |

#### \`git-*\` roles

Diff and PR/CR-state colors — \`added\`, \`removed\`, \`modified\`, \`conflicting\`, \`merged\`, \`closed\`, \`draft\`, plus \`opened\`/\`queued\` as aliases of \`added\`/\`modified\`. Each carries the full \`text\` / \`fill{,-hover}\` / \`bg\` / \`border\` / \`on\` suite. Values come from \`@ant/epitaxy\`'s \`--extended-*\` palette (not CDS ramp stops), so migrating claude.ai's diff UI onto these tokens is a rename; \`fill\` light is the Epitaxy hue darkened just enough for white \`on-git-*\` to pass AA.

### Background vs. fill

Both are backgrounds; the split is saturation, and therefore which foreground token pairs on top.

\`bg-{role}\` is the pale tint (hue-100 light / hue-800 dark) for passive status surfaces — Banner, Badge, chip. Light enough that \`text-{role}\` (hue-600) reads against it: a danger banner is \`bg-danger\` + \`text-danger\`. \`fill-{role}\` is the saturated solid (hue-450) for interactive controls — button, checkbox, toggle. Too dark for \`text-{role}\`, so it pairs with \`on-{role}\` (gray-0 / gray-900) instead; the 450 stop is chosen for WCAG contrast against \`on-*\`.

|       | Background    | Foreground    | Example       |
| ----- | ------------- | ------------- | ------------- |
| Tint  | \`bg-{role}\`   | \`text-{role}\` | Banner, Badge |
| Solid | \`fill-{role}\` | \`on-{role}\`   | Button        |

The token name encodes the pairing: use \`bg-*\` when the hue is ambient context behind body text; \`fill-*\` when the hue _is_ the control surface.

### Purpose tokens

| Token                        | Value (light)                                            | Use case                                         |
| ---------------------------- | -------------------------------------------------------- | ------------------------------------------------ |
| \`--text-primary\`         | \`neutral-900\`                                            | Body text                                        |
| \`--text-secondary\`       | \`neutral-600\`                                            | Supporting text                                  |
| \`--text-muted\`           | \`neutral-400\`                                            | Placeholder, captions                            |
| \`--text-disabled\`        | \`alpha-4\`                                                | Disabled labels                                  |
| \`--border\`               | \`alpha-2\`                                                | Default 1px hairline                             |
| \`--border-strong\`        | \`alpha-3\`                                                | Emphasized divider                               |
| \`--border-stronger\`      | \`neutral-900 / 40%\`                                      | Heavy divider                                    |
| \`--fill-primary\`         | \`neutral-900\`                                            | Primary button bg                                |
| \`--fill-primary-hover\`   | \`neutral-750\`                                            |                                                  |
| \`--fill-secondary\`       | \`hsl(0 0% 100% / 0.1)\`                                   | Secondary button bg                              |
| \`--fill-secondary-hover\` | \`alpha-1\`                                                |                                                  |
| \`--fill-secondary-ring\`  | \`border\` (light) / transparent (dark)                    | Secondary button ring                            |
| \`--fill-field\`           | \`hsl(0 0% 100% / 0.5)\` (light) / \`fill-secondary\` (dark) | Field control bg (TextInput, TextArea, Combobox) |
| \`--fill-ghost-hover\`     | \`alpha-1\`                                                | Ghost button hover bg                            |
| \`--fill-control\`         | \`alpha-2\`                                                | Avatar fallback bg                               |
| \`--fill-control-hover\`   | \`alpha-3\`                                                |                                                  |
| \`--fill-disabled\`        | \`alpha-1\`                                                | Disabled control bg                              |
| \`--on-primary\`           | \`neutral-0\`                                              | Text on \`fill-primary\`                           |
| \`--on-accent\`            | \`gray-0\`                                                 | Text on \`accent\`                                 |
| \`--on-brand\`             | \`gray-0\`                                                 | Text on \`brand\`                                  |
| \`--on-danger\`            | \`gray-0\`                                                 | Text on \`danger\`                                 |
| \`--on-success\`           | \`gray-900\`                                               | Text on \`success\`                                |
| \`--on-warning\`           | \`gray-900\`                                               | Text on \`warning\`                                |
| \`--on-pro\`               | \`gray-0\`                                                 | Text on \`pro\`                                    |
| \`--focus-shadow\`         | \`0 0 0 1px accent, 0 0 6px 1px bg-accent\`                | \`focus-visible\` ring                             |
| \`--shadow-sm\`            | two-layer via \`--shadow-color\`                       | Low elevation                                    |
| \`--shadow-md\`            | two-layer via \`--shadow-color\`                       | Card / panel                                     |
| \`--shadow-lg\`            | two-layer via \`--shadow-color\`                       | Dialog / sheet                                   |
| \`--shadow-popover\`       | \`0 8px 24px /12%, 0 2px 6px /8%\`                         | Menu, dropdown popups                            |
| \`--surface-popover\`      | \`surface-3\`                                              | Named alias                                      |
| \`--surface-panel\`        | \`surface-2\`                                              | Named alias                                      |

\`--shadow-sm/md/lg\` are two-layer composites (contact + diffused drop) driven by \`--shadow-color\`, which deepens to \`black/24%\` in dark mode (epitaxy parity). \`--shadow-popover\` is a fixed two-layer literal tuned for floating menus.

---

## CDS content

How to write the words that go inside cds components. Tokens decide how the UI _looks_; this decides how it _sounds_.

The voice is **intelligent, warm, unvarnished, and collaborative** — your smartest friend explaining something in plain terms. Friendly lives in the copy, not in extra chrome.

## Mechanics

- **Sentence case everywhere.** Buttons, headings, tabs, labels, menu items. "Save changes", not "Save Changes". Title Case is for proper nouns only (Claude, Opus, Anthropic Console).
- **No terminal punctuation on labels and headings.** Helper text, descriptions, and empty-state body copy _do_ end with a period.
- **Use contractions.** "Can't", "you'll", "it's". Conversational, not stiff.
- **Active voice, verb first.** "Delete project", not "Project deletion".
- **Ellipsis = in progress only.** "Claude is thinking…". Not for trailing off, not for menu suffixes.
- **No ampersands.** Spell out "and".
- **Serial comma.** "Chats, projects, and artifacts."

## Pronouns

UI speaks as the product, not as Claude and not as the user.

| Context          | Use               | Example                                                 |
| ---------------- | ----------------- | ------------------------------------------------------- |
| User's things    | **your**          | "Your projects" — never "My projects"                   |
| Confirmations    | none / past tense | "Saved", "Got it" — never "I saved it"                  |
| Errors           | **you / your**    | "Your session expired" — never "I couldn't…"            |
| Claude (in chat) | **I**             | Reserved for the chat surface; system UI never says "I" |

## Words to avoid

| Skip                                        | Why                                   | Instead          |
| ------------------------------------------- | ------------------------------------- | ---------------- |
| "successfully"                              | The success toast _is_ the success    | "File uploaded"  |
| "please"                                    | UI isn't asking a favor               | "Enter a name"   |
| "Click here" / "Tap to…"                    | Link text should name the destination | "Read the docs"  |
| "!" on system copy                          | Reads as shouty                       | "Settings saved" |
| "leverage", "seamless", "unlock", "empower" | Corporate filler                      | Say what it does |
| "simply", "just", "easy"                    | Presumes — and condescends            | Cut it           |

## Patterns

**Buttons / CTAs** — verb first, 1–3 words, sentence case, no punctuation. "Create project", "Upgrade to Pro". Not "OK", "Submit", or "Click to continue".

**Errors** — say what happened, then what to do. One sentence, no "Error:" prefix, no first person. "That name's already taken. Try another." Never surface raw exception strings.

**Empty states** — an invitation, not an apology. Headline names the space ("Start your first project"), one-line body explains it, CTA is a verb ("Create project"). Skip "Nothing here yet."

**Placeholders** — a real example of valid input ("name@company.com", "Summarize this document"). No "e.g." prefix, don't repeat the field label.

**Links** — describe where they go ("Learn more", "View pricing"). Keep them at the end of the sentence; punctuation sits outside the link.

## Do / Don't

| Do                                 | Don't                                  |
| ---------------------------------- | -------------------------------------- |
| "File uploaded"                    | "Your file was uploaded successfully!" |
| "Enter a workspace name"           | "Please enter a workspace name."       |
| "Couldn't connect to Slack. Retry" | "Error: I was unable to connect."      |
| "Your projects"                    | "My projects"                          |
| "Create project"                   | "Click Here To Get Started"            |
| "Connect Slack"                    | "Add the Slack Connector"              |
`
